Ti=CONTRAT DE CESSION DE DROITS DE PROPRIÉTÉ INTELLECTUELLE ( ASSOCIÉ ) 
0.1.sec=ENTRE LES SOUSSIGNÉ(E)S :<br><br>
0.2.sec=Monsieur ou Madame {Nom_Prénom}
0.3.sec=Né(e) le {Date_Naissance} à {Lieu_Naissance}
0.4.sec=De nationalité {Nationalité}
0.5.sec=Exerçant la profession de {Profession}
0.6.sec=Demeurant {Adresse_Domicile}
0.7.sec=Ci-après dénommé(e) le "Cédant",
0.8.sec=D'une part,<br><br>
0.9.sec=ET:<br><br>
0.10.sec=La société {Nom_Société}
0.11.sec={Forme_Société} au capital de {Capital_Société_Chiffres} euros
0.12.sec=Immatriculée au RCS de {Ville-Immatriculation} sous le numéro {Num_CRS}
0.13.sec=Dont le siège social est situé {Adresse_SiègeSocial}
0.14.sec= Représentée par Monsieur ou Madame {Nom_Prénom_Représentant} en qualité de {Président_Gérant_DirecteurG} dûment habilité aux fins des présentes,
0.15.sec=Ci-après dénommée le "Cessionnaire", 
0.16.sec=D'autre part, 
0.17.sec=Ci-après individuellement ou collectivement désigné(s) la ou les Partie(s)
0.18.sec=Etant préalablement rappelé que :<br><br>
0.19.sec=- Le Cédant est un des associés du Cessionnaire.
0.20.sec=- Dans le cadre de sa participation en tant qu'associé, le Cédant sera amené à réaliser des travaux susceptibles d'être protégés par un droit de propriété intellectuelle.
0.21.sec=- Il est ainsi apparu nécessaire aux Parties que les droits de propriété y afférents soient cédés au Cessionnaire.
0.22.sec=- Les Parties se sont donc rapprochées pour formaliser la présente cession.<br><br>
0.23.sec=Il a été convenu ce qui suit :<br><br>
0.=[Z/paras/s23]
1.0.sec= Objet de la cession<br><br>
1.1.sec=Par les présentes, le Cédant cède au Cessionnaire, sans restriction ni réserve, l'intégralité des droits d'auteur relatifs aux logiciels qu'il pourra réaliser dans l'exercice de ses fonctions et missions (ci-après dénommés les « Logiciels »), tel que ces droits sont énumérés ci-dessous, à savoir :<br><br>
1.2.sec=- Le droit de reproduction et d'utilisation des Logiciels pour quelque usage que ce soit, par tous moyens, notamment internet, sur tous supports, existants ou à venir, prévisibles ou imprévisibles, et pour toute exploitation ;<br><br>
1.3.sec=- Le droit de représentation publique et de diffusion des Logiciels, sur tous supports et par tous moyens, notamment internet, existants ou à venir, prévisibles ou imprévisibles ;<br><br>
1.4.sec=- Le droit de traduire, arranger, modifier, intégrer, transformer, adapter et corriger les Logiciels, à l'initiative du Cessionnaire ou avec la collaboration d'une tierce personne ;<br><br>
1.5.sec=- Le droit d'associer les Logiciels avec tous éléments visuels, sonores, audiovisuels, multimédia et/ou textuels ;<br><br>
1.6.sec=- Le droit de réutiliser les Logiciels, en totalité ou en partie, afin de réaliser et exploiter notamment tous autres logiciels, sites internet, jeux, applications, ou tous autres produits au choix du Cessionnaire ;<br><br>
1.7.sec=- Le droit de commercialiser et d'exploiter les Logiciels à toutes fins ;<br><br>
1.8.sec=- Ainsi que le droit de transférer à des tiers l'usage ou la propriété de tout ou partie des droits présentement cédés, selon les conditions et modalités qu'il jugera les plus appropriées.<br><br>
1.9.sec=Cette cession est consentie à titre exclusif et définitif, pour toute la durée du droit et pour le monde entier<br><br>
1.=[Z/paras/s9]
2.0.sec=Le Cédant s'engage à communiquer régulièrement au Cessionnaire une liste exhaustive des Logiciels, au fur et à mesure de leur réalisation, et à lui remettre les codes-source, codes-objet et toute la documentation afférente aux Logiciels, dont la propriété matérielle est cédée irrévocablement, sans restriction ni réserve, au Cessionnaire dans le cadre du présent contrat.<br><br>
2.1.sec=Par les présentes, le Cédant cède également au Cessionnaire, sans restriction ni réserve, l'intégralité des droits d'auteur relatifs aux autres œuvres de l'esprit, hors logiciels, qu'il pourra réaliser dans l'exercice de ses fonctions et missions (ci-après dénommées les « Créations »), tel que ces droits sont numérés ci-dessous, à savoir :<br><br>
2.2.sec=-Le droit de reproduire les Créations, en totalité ou en partie, en tout format, sur tout support notamment imprimé, magnétique, électronique et numérique, sur tout produit, de quelque nature qu'il soit et par tout procédé matériel ou immatériel, existants ou à venir, prévisibles ou imprévisibles ;<br><br>
2.3.sec=-Le droit de fabriquer ou faire fabriquer, éditer, distribuer, diffuser et commercialiser les Créations, en autant d'exemplaires qu'il plaira au Cessionnaire, en tout ou en partie et dans tous circuits de commercialisation ;<br><br>
2.4.sec=-Le droit de représenter publiquement les Créations, en totalité ou en partie, en tout lieu physique, à travers tous médias, tous réseaux informatiques et tous moyens de diffusion, de quelque nature qu'ils soient, existants ou à venir, prévisibles ou imprévisibles, tels que, sans que cette liste soit limitative, par internet, téléphonie mobile et télédiffusion;<br><br>
2.5.sec=- Le droit d'adapter, traduire, modifier, arranger, transformer et corriger les Créations, notamment, sans que cette liste soit limitative, à travers la retouche, le recadrage, le changement de format ou de couleurs des Créations ou encore l'apposition sur celles-ci, par le Cessionnaire, de son nom, de sa marque et de son logo, pour tenir compte en particulier de contraintes techniques, matérielles ou commerciales ou pour tout autre motif légitime, sous réserve du respect du droit moral du Cédant,<br><br>
2.6.sec=- Le droit d'utiliser les Créations, en totalité ou en partie, afin de les associer avec, incorporer dans ou exploiter à travers, sans que cette liste soit limitative, tous éléments visuels, sonores et/ou textuels et tous produits, notamment tous produits multimédia ou audiovisuels, sites internet, jeux, applications ;<br><br>
2.7.sec=- Le droit d'utiliser les reproductions et/ou représentations des Créations réalisées selon les modalités décrites ci-dessus, à des fins promotionnelles, commerciales ou non, ainsi que de les diffuser à titre gratuit ou payant ;<br><br>
2.8.sec=- Le droit d'utiliser tout ou partie des Créations aux fins d'exploitations dérivées (communément désignées sous le nom de « merchandising »), notamment en vue de fabriquer et diffuser des produits commerciaux, de quelque nature que ce soit, et de les distribuer, en particulier dans les domaines des jeux, jouets, objets ou œuvres d'art plastique ou arts appliqués, papeterie, bureautique, fonds d'écran, articles de bureau, habillement, ameublement, articles de décoration, arts de la table, toilette, hygiène, alimentation ;<br><br>
2.9.sec=- Le droit pour le Cessionnaire d'effectuer toutes démarches et de procéder à toutes formalités, y compris de renouvellement éventuel, en vue du dépôt et de l'enregistrement des Créations auprès de tout organisme habilité sur le fondement du droit des marques, des dessins et modèle ou de toute autre protection reconnue au titre de la propriété intellectuelle ;<br><br>
2.10.sec=- Ainsi que le droit de transférer à des tiers l'usage ou la propriété de tout ou partie des droits présentement cédés, selon les conditions et modalités qu'il jugera les plus appropriées.<br><br>
2.11.sec=Cette cession est consentie à titre exclusif et définitif, pour toute la durée légale du droit d'auteur et pour le monde entier.<br><br>
2.12.sec=Le Cédant s'engage à communiquer régulièrement au Cessionnaire une liste exhaustive des Créations, au fur et à mesure de leur réalisation, et à lui remettre les Créations sous leur support original, ainsi que toutes copies qui en auraient été faites et plus généralement, toute documentation en relation avec les Créations, dont la propriété matérielle est cédée irrévocablement, sans restriction ni réserve, au Cessionnaire dans le cadre du présent contrat.<br><br>
2.13.sec=Le Cédant cède au Cessionnaire sans restriction ni réserve, l'intégralité de ses droits afférents aux inventions, brevetables ou non, et à tous brevets d'invention (ci-après dénommées : les « Inventions »), dont il sera l'inventeur dans le cadre de l'exercice de ses fonctions et missions et, plus généralement, dans le domaine des activités du Cessionnaire ou par la connaissance ou l'utilisation d'informations ou de moyens appartenant au Cessionnaire.<br><br>
2.14.sec=Cette cession est consentie à titre exclusif et définitif, pour toute la durée légale de protection des droits concernés et pour le monde entier.<br><br>
2.15.sec=Le Cessionnaire sera ainsi seul habilité à exploiter les Inventions et à effectuer toutes formalités de dépôt en son nom, s'il l'estime nécessaire, le Cédant à l'origine des Inventions pouvant toutefois, s'il le souhaite, être mentionné comme inventeur. Le Cédant s'engage à signer tout document et à procéder à toute formalité nécessaire auprès de tout organisme concerné pour permettre au Cessionnaire de faire valoir ses droits.<br><br>
2.16.sec=Par dérogation aux dispositions qui précèdent, dans l'hypothèse où le Cédant serait bénéficiaire d'un contrat de travail, il sera alors fait application des dispositions légales et conventionnelles applicables, notamment l'article L.611-7 du Code de la propriété intellectuelle.<br><br>
2.17.sec=Le Cédant s'engage à communiquer régulièrement au Cessionnaire une liste exhaustive des Inventions, au fur et à mesure de leur réalisation, et à lui remettre tous travaux, études, recherches et documents relatifs aux Inventions, dont la propriété matérielle est cédée irrévocablement, sans restriction ni réserve, au Cessionnaire dans le cadre du présent contrat.<br><br>
2.=[Z/paras/s17]
3.0.sec=Garantie du Cédant<br><br> 
3.1.sec=Le Cédant garantit au Cessionnaire la jouissance entière et paisible des droits cédés contre tous troubles, actions revendications ou évictions quelconques.<br><br>
3.2.sec=Il garantit ainsi notamment au Cessionnaire qu'il dispose de tous les droits et autorisations nécessaires pour consentir la présente cession et que les Logiciels, Créations et Inventions ne contiennent rien qui puisse tomber sous le coup des lois et règlements relatifs notamment à la contrefaçon, la concurrence déloyale, la vie privée, le droit à l'image, les droits de la personnalité et plus généralement, contrevenir aux droits des tiers.<br><br>
3.3.sec=Le Cédant garantit le Cessionnaire contre toutes plaintes, réclamations et/ou revendications quelconques de la part d'un tiers que le Cessionnaire pourrait subir du fait de la violation, par le Cédant, des garanties ci-dessus. Il s'engage à indemniser le Cessionnaire de tout préjudice qu'il subirait et à lui payer tous les frais, indemnités, charges et/ou condamnations qu'il pourrait avoir à supporter de ce fait.<br><br>
3.=[Z/paras/s3]
4.0.sec=Cession à titre gratuit<br><br>
4.1.sec=La cession prévue aux articles 1.1 à 1.6 des présentes est consentie à titre gratuit<br><br>
4.=[Z/paras/s1]
5.0.sec=Loi applicable et juridiction<br><br> 
5.1.sec= Le présent contrat est soumis au droit français et sera régi et interprété selon ce droit.
5.2.sec= Tout litige pouvant naître à l'occasion de sa validité, de son interprétation ou de son exécution sera soumis à la compétence exclusive des Tribunaux de Paris, sauf règle de procédure impérative contraire.
5.3.sec= Fait à {ville}, le {date},
5.4.sec= En deux exemplaires originaux.
5.5.sec= Pour le Cédant {Nom_prénom_signataire}
5.6.sec= Pour le Cessionnaire{Nom_prénom_signataire}
5.=[Z/ol-none/s6]
=[Z/ol/s5]   
